=== Cryotechnic/Questionable-Wiggly/Questionable/QuestSchema/schema_v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/quest/1.0",
  "title": "Questionable V1",
  "description": "A series of quest sequences",
  "type": "object",
  "properties": {
    "Version": {
      "description": "Version of the schema",
      "type": "integer",
      "minimum": 1,
      "maximum": 1
    },
    "Author": {
      "description": "Author of the quest sequence",
      "type": "string"
    },
    "Contributors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Comment": {
      "type": "string"
    },
    "TerritoryBlacklist": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "QuestSequence": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Sequence": {
            "type": "integer",
            "minimum": 0,
            "maximum": 255
          },
          "Steps": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "DataId": {
                  "type": "integer",
                  "exclusiveMinimum": 0
                },
                "Position": {
                  "type": "object",
                  "properties": {
                    "X": {
                      "type": "number"
                    },
                    "Y": {
                      "type": "number"
                    },
                    "Z": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "X",
                    "Y",
                    "Z"
                  ]
                },
                "TerritoryId": {
                  "type": "integer",
                  "exclusiveMinimum": 0
                },
                "InteractionType": {
                  "type": "string",
                  "enum": [
                    "Interact",
                    "AttuneAethenetShard",
                    "AttuneAetheryte",
                    "AetherCurrent",
                    "Combat",
                    "UseItem",
                    "Emote",
                    "ManualAction"
                  ]
                },
                "Disabled": {
                  "type": "boolean"
                },
                "AethernetShortcut": {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": {
                    "type": "string",
                    "enum": [
                      "[The Crystarium] Aetheryte Plaza",
                      "[The Crystarium] Musica Universalis Markets",
                      "[The Crystarium] Themenos Rookery",
                      "[The Crystarium] The Dossal Gate",
                      "[The Crystarium] The Pendants",
                      "[The Crystarium] The Amaro Launch",
                      "[The Crystarium] The Crystalline Mean",
                      "[The Crystarium] The Cabinet of Curiosity",
                      "[Eulmore] Aetheryte Plaza",
                      "[Eulmore] Southeast Derelicts",
                      "[Eulmore] Nightsoil Pots",
                      "[Eulmore] The Glory Gate",
                      "[Eulmore] The Mainstay",
                      "[Old Sharlayan] Aetheryte Plaza",
                      "[Old Sharlayan] The Studium",
                      "[Old Sharlayan] The Baldesion Annex",
                      "[Old Sharlayan] The Rostra",
                      "[Old Sharlayan] The Leveilleur Estate",
                      "[Old Sharlayan] Journey's End",
                      "[Old Sharlayan] Scholar's Harbor",
                      "[Radz-at-Han] Aetheryte Plaza",
                      "[Radz-at-Han] Meghaduta",
                      "[Radz-at-Han] Ruveydah Fibers",
                      "[Radz-at-Han] Airship Landing",
                      "[Radz-at-Han] Alzadaal's Peace",
                      "[Radz-at-Han] Hall of the Radiant Host",
                      "[Radz-at-Han] Mehryde's Meyhane",
                      "[Radz-at-Han] Kama",
                      "[Radz-at-Han] The High Crucible of Al-Kimiya"
                    ]
                  }
                },
                "KillEnemyDataIds": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  }
                },
                "Emote": {
                  "type": "string",
                  "enum": [
                    "stretch",
                    "wave",
                    "rally"
                  ]
                },
                "SkipIf": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "enum": [
                      "FlyingUnlocked"
                    ]
                  }
                },
                "Comment": {
                  "type": "string"
                }
              },
              "required": [
                "TerritoryId",
                "InteractionType"
              ]
            }
          },
          "Comment": {
            "type": "string"
          }
        },
        "required": [
          "Sequence"
        ]
      }
    }
  },
  "required": [
    "Version",
    "Author"
  ]
}

=== Cryotechnic/Questionable-Wiggly/Questionable/QuestPaths/Endwalker-B-Garlemald/4383_A Frosty Reception.json
{
  "Version": 1,
  "Author": "liza",
  "TerritoryBlacklist": [
    1010
  ],
  "QuestSequence": [
    {
      "Sequence": 0,
      "Steps": [
        {
          "DataId": 1038824,
          "Position": {
            "X": 750.97266,
            "Y": 69.99991,
            "Z": 534.78296
          },
          "TerritoryId": 621,
          "InteractionType": "Interact"
        }
      ]
    },
    {
      "Sequence": 1,
      "Steps": [
        {
          "DataId": 1038825,
          "Position": {
            "X": 742.5803,
            "Y": 69.99999,
            "Z": 539.6046
          },
          "TerritoryId": 621,
          "InteractionType": "ManualAction",
          "Comment": "Duty - A Frosty Reception"
        }
      ]
    },
    {
      "Sequence": 3,
      "Steps": [
        {
          "DataId": 172,
          "Position": {
            "X": -408.0791,
            "Y": 24.18463,
            "Z": 479.9764
          },
          "StopDistance": 7,
          "TerritoryId": 958,
          "InteractionType": "AttuneAetheryte"
        },
        {
          "DataId": 1038826,
          "Position": {
            "X": -399.31335,
            "Y": 22.03761,
            "Z": 454.45935
          },
          "TerritoryId": 958,
          "InteractionType": "Interact"
        }
      ]
    },
    {
      "Sequence": 4,
      "Steps": [
        {
          "DataId": 1038836,
          "Position": {
            "X": -439.9939,
            "Y": 22.000002,
            "Z": 497.79492
          },
          "TerritoryId": 958,
          "InteractionType": "Interact"
        }
      ]
    },
    {
      "Sequence": 5,
      "Steps": [
        {
          "DataId": 1038835,
          "Position": {
            "X": -366.17078,
            "Y": 22,
            "Z": 514.4884
          },
          "TerritoryId": 958,
          "InteractionType": "Interact"
        }
      ]
    },
    {
      "Sequence": 6,
      "Steps": [
        {
          "DataId": 1038828,
          "Position": {
            "X": -334.5846,
            "Y": 23.803606,
            "Z": 404.65393
          },
          "StopDistance": 7,
          "TerritoryId": 958,
          "InteractionType": "Interact"
        }
      ]
    },
    {
      "Sequence": 255,
      "Steps": [
        {
          "DataId": 1038837,
          "Position": {
            "X": -353.41425,
            "Y": 22.717295,
            "Z": 435.62976
          },
          "StopDistance": 5,
          "TerritoryId": 958,
          "InteractionType": "Interact"
        }
      ]
    }
  ]
}

=== Cryotechnic/Questionable-Wiggly/Questionable/QuestPaths/Endwalker-B-Garlemald/4398_The Martyr.json
{
  "Version": 1,
  "Author": "liza",
  "TerritoryBlacklist": [
    992
  ],
  "QuestSequence": [
    {
      "Sequence": 0,
      "Steps": [
        {
          "DataId": 1039987,
          "Position": {
            "X": 189.25769,
            "Y": 63.36112,
            "Z": 467.46008
          },
          "TerritoryId": 959,
          "InteractionType": "Interact"
        }
      ]
    },
    {
      "Sequence": 1,
      "Steps": [
        {
          "DataId": 1039987,
          "Position": {
            "X": 189.25769,
            "Y": 63.36112,
            "Z": 467.46008
          },
          "TerritoryId": 959,
          "InteractionType": "Interact"
        }
      ]
    },
    {
      "Sequence": 2,
      "Steps": [
        {
          "DataId": 2012122,
          "Position": {
            "X": 99.96179,
            "Y": -0.015319824,
            "Z": 103.227295
          },
          "TerritoryId": 1028,
          "InteractionType": "ManualAction",
          "Comment": "Duty - Zodiark"
        }
      ]
    },
    {
      "Sequence": 255,
      "Steps": [
        {
          "DataId": 1039989,
          "Position": {
            "X": -279.95728,
            "Y": 76.14732,
            "Z": 480.91858
          },
          "StopDistance": 5,
          "TerritoryId": 959,
          "InteractionType": "Interact"
        }
      ]
    }
  ]
}
